schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "02-conveyor-belt"
owner:
  username: "S255153"
  id: 321073548
  accepted_at: "2026-09-09T12:13:38Z"
source:
  owner: "dtucprog"
  owner_id: 316954301
  repo: "02-conveyor-belt"
  branch: "main"
